# Generated by Django 3.1.6 on 2021-02-05 07:15

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('sections', wagtail.core.fields.StreamField([('BlogPost', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('post', wagtail.core.blocks.RichTextBlock()), ('gallery', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock())]))]))], null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
