# Generated by Django 3.1.6 on 2021-02-05 07:27

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210205_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='sections',
            field=wagtail.core.fields.StreamField([('BlogPost', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('post', wagtail.core.blocks.RichTextBlock())]))], null=True),
        ),
    ]
