# Generated by Django 3.1.6 on 2021-02-04 14:44

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='sections',
            field=wagtail.core.fields.StreamField([('about', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock()), ('picture', wagtail.images.blocks.ImageChooserBlock())], blank=True, null=True))], null=True),
        ),
    ]
