# Generated by Django 3.1.6 on 2021-02-04 11:03

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('sections', wagtail.core.fields.StreamField([('header', wagtail.core.blocks.StructBlock([], blank=True, null=True)), ('about', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('name', wagtail.core.blocks.CharBlock()), ('description', wagtail.core.blocks.RichTextBlock()), ('picture', wagtail.images.blocks.ImageChooserBlock())], blank=True, null=True)), ('projects', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('foreword', wagtail.core.blocks.RichTextBlock()), ('projects', wagtail.core.blocks.StreamBlock([('project', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('description', wagtail.core.blocks.RichTextBlock()), ('gallery', wagtail.core.blocks.StreamBlock([('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('description', wagtail.core.blocks.RichTextBlock())]))]))]))]))], blank=True, null=True)), ('footer', wagtail.core.blocks.StructBlock([], blank=True, null=True))], blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
