# Generated by Django 3.1.6 on 2021-02-04 12:13

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20210204_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliopage',
            name='sections',
            field=wagtail.core.fields.StreamField([('header', wagtail.core.blocks.StructBlock([], blank=True, null=True)), ('about', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('name', wagtail.core.blocks.CharBlock()), ('description', wagtail.core.blocks.RichTextBlock()), ('picture', wagtail.images.blocks.ImageChooserBlock())], blank=True, null=True)), ('projects', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('foreword', wagtail.core.blocks.RichTextBlock()), ('projects', wagtail.core.blocks.StreamBlock([('project', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('description', wagtail.core.blocks.RichTextBlock()), ('gallery', wagtail.core.blocks.StreamBlock([('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('description', wagtail.core.blocks.RichTextBlock())]))]))]))]))], blank=True, null=True)), ('footer', wagtail.core.blocks.StructBlock([], blank=True, null=True))], blank=True, null=True),
        ),
    ]
